---
title: "case study"
author: "Luan Mengxiao"
date: 2023-10-10
output: github_document
---

# set up

```{r}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# import data

```{r}
library(p8105.datasets)
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |>
  rename(borough = neighbourhood_group) |>
  mutate(stars = review_scores_location / 2)
```

# brainstorm questions

* Where are airbnbs expensive?
  - Borough? Neighbourhood?
  - Do other factors (room type) affect price? What about rating?
* How long are airbnbs active?
  - Are they illegal and do they get shut down?
* Which units have the most availability?
* How is review score impacted by location?
* How many apts are run by one host?